// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4nh1r2458mb8j8t.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5oMXIyNDU4bWI4ajh0IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODk2OTk2ODEsImV4cCI6MjEwNTI3NTY4MX0.zSWkRpAguQSP2o_oeDKFJJoQ3LH60EGZRly1AurzZNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
